version: '3'
services:

## Router
  router01:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: receipt-router-1
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all --keyFile /data/mongodb-keyfile
    ports:
      - 27217:27017
    restart: always
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_router01_db:/data/db
      - mongodb_cluster_router01_config:/data/configdb
  router02:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: receipt-router-2
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_router02_db:/data/db
      - mongodb_cluster_router02_config:/data/configdb
    ports:
      - 27218:27017
    restart: always
    links:
      - router01

## Config Servers
  configsvr01:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: mongo-config-receipt-01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts 
      - mongodb_cluster_configsvr01_db:/data/db
      - mongodb_cluster_configsvr01_config:/data/configdb
    ports:
      - 27219:27017
    restart: always
    links:
      - shard01-a
      - shard02-a
      - shard03-a
      - configsvr02
      - configsvr03
  configsvr02:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: mongo-config-receipt-02 
    command: mongod --port 27017 --configsvr --replSet rs-config-server --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvr02_db:/data/db
      - mongodb_cluster_configsvr02_config:/data/configdb
    ports:
      - 27220:27017
    restart: always
  configsvr03:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: mongo-config-receipt-03 
    command: mongod --port 27017 --configsvr --replSet rs-config-server --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvr03_db:/data/db
      - mongodb_cluster_configsvr03_config:/data/configdb
    ports:
      - 27221:27017
    restart: always


## Shards
  ## Shards 01
   
  shard01-a:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2 
    container_name: shard-01-receipt-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01-receipt --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_a_db:/data/db
      - mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27222:27017
    restart: always
    links:
      - shard01-b
      - shard01-c
  shard01-b:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: shard-01-receipt-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01-receipt --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_b_db:/data/db
      - mongodb_cluster_shard01_b_config:/data/configdb
    ports:
      - 27223:27017
    restart: always
  shard01-c:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: shard-01-receipt-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01-receipt --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_c_db:/data/db
      - mongodb_cluster_shard01_c_config:/data/configdb
    ports:
      - 27224:27017
    restart: always

  ## Shards 02
  shard02-a:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: shard-02-receipt-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02-receipt --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_a_db:/data/db
      - mongodb_cluster_shard02_a_config:/data/configdb
    ports:
      - 27225:27017
    restart: always
    links:
      - shard02-b
      - shard02-c
  shard02-b:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: shard-02-receipt-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02-receipt --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_b_db:/data/db
      - mongodb_cluster_shard02_b_config:/data/configdb
    ports:
      - 27226:27017
    restart: always
  shard02-c:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: shard-02-receipt-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02-receipt --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_c_db:/data/db
      - mongodb_cluster_shard02_c_config:/data/configdb
    ports:
      - 27227:27017
    restart: always

  ## Shards 03
  shard03-a:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: shard-03-receipt-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03-receipt --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard03_a_db:/data/db
      - mongodb_cluster_shard03_a_config:/data/configdb
    ports:
      - 27228:27017
    restart: always
    links:
      - shard03-b
      - shard03-c
  shard03-b:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: shard-03-receipt-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03-receipt --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard03_b_db:/data/db
      - mongodb_cluster_shard03_b_config:/data/configdb
    ports:
      - 27229:27017
    restart: always
  shard03-c:
    build: 
      context: mongodb-build
    image: jin-mongo:6.0.2
    container_name: shard-03-receipt-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03-receipt --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard03_c_db:/data/db
      - mongodb_cluster_shard03_c_config:/data/configdb
    ports:
      - 27230:27017
    restart: always

volumes:
  mongodb_cluster_router01_db:
  mongodb_cluster_router01_config:
  
  mongodb_cluster_router02_db:
  mongodb_cluster_router02_config:
  
  mongodb_cluster_configsvr01_db:
  mongodb_cluster_configsvr01_config:
  
  mongodb_cluster_configsvr02_db:
  mongodb_cluster_configsvr02_config:
  
  mongodb_cluster_configsvr03_db:
  mongodb_cluster_configsvr03_config:
  
  mongodb_cluster_shard01_a_db:
  mongodb_cluster_shard01_a_config:
  
  mongodb_cluster_shard01_b_db:
  mongodb_cluster_shard01_b_config:
  
  mongodb_cluster_shard01_c_db:
  mongodb_cluster_shard01_c_config:
  
  mongodb_cluster_shard02_a_db:
  mongodb_cluster_shard02_a_config:
  
  mongodb_cluster_shard02_b_db:
  mongodb_cluster_shard02_b_config:
  
  mongodb_cluster_shard02_c_db:
  mongodb_cluster_shard02_c_config:
  
  mongodb_cluster_shard03_a_db:
  mongodb_cluster_shard03_a_config:
  
  mongodb_cluster_shard03_b_db:
  mongodb_cluster_shard03_b_config:
  
  mongodb_cluster_shard03_c_db:
  mongodb_cluster_shard03_c_config:
