version: '3'
services:

## Router
  router01:
    image: mongo:5.0
    container_name: receipt-router-1
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017 --bind_ip_all
    ports:
      - 27217:27017
    volumes:
      - ./scripts:/scripts


## Config Servers
  configsvr01:
    image: mongo:5.0
    container_name: mongo-config-receipt-01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts 
    ports:
      - 27219:27017
    links:
      - shard01-a
      - shard02-a
      - shard03-a
  

## Shards
  ## Shards 01
   
  shard01-a:
    image: mongo:5.0
    container_name: mongo-config-receipt-receipt-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27222:27017
    links:
      - shard01-b
      - shard01-c
  shard01-b:
    image: mongo:5.0
    container_name: shard-01-receipt-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27223:27017
  shard01-c:
    image: mongo:5.0
    container_name: shard-01-receipt-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27224:27017

  ## Shards 02
  shard02-a:
    image: mongo:5.0
    container_name: shard-02-receipt-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27225:27017
    links:
      - shard02-b
      - shard02-c
  shard02-b:
    image: mongo:5.0
    container_name: shard-02-receipt-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27226:27017
  shard02-c:
    image: mongo:5.0
    container_name: shard-02-receipt-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27227:27017

  ## Shards 03
  shard03-a:
    image: mongo:5.0
    container_name: shard-03-receipt-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27228:27017
    links:
      - shard03-b
      - shard03-c
  shard03-b:
    image: mongo:5.0
    container_name: shard-03-receipt-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27229:27017
  shard03-c:
    image: mongo:5.0
    container_name: shard-03-receipt-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27230:27017