version: '2'
services:

## Router
  router01:
    image: mongo
    container_name: receipt-router-1
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27217:27017
    volumes:
      - ./scripts:/scripts
  router02:
    image: mongo
    container_name: receipt-router-2
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
    ports:
      - 27218:27017
    links:
      - router01

## Config Servers
  configsvr01:
    image: mongo
    container_name: mongo-config-receipt-01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts 
    ports:
      - 27219:27017
    links:
      - shard01-a
      - shard02-a
      - shard03-a
  configsvr02:
    image: mongo
    container_name: mongo-config-receipt-02 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
    ports:
      - 27220:27017
    links:
      - configsvr01
  configsvr03:
    image: mongo
    container_name: mongo-config-receipt-03 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
    ports:
      - 27221:27017
    links:
      - configsvr02

## Shards
  ## Shards 01
  shard01-x:
    image: mongo
    container_name: shard-01-receipt-node-x
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27222:27017
    links:
      - shard01-a
      - shard01-b
  shard01-a:
    image: mongo
    container_name: shard-01-receipt-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27223:27017
  shard01-b:
    image: mongo
    container_name: shard-01-receipt-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27224:27017

  ## Shards 02
  shard02-x:
    image: mongo
    container_name: shard-02-receipt-node-x
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27225:27017
    links:
      - shard02-a
      - shard02-b
  shard02-a:
    image: mongo
    container_name: shard-02-receipt-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27226:27017
  shard02-b:
    image: mongo
    container_name: shard-02-receipt-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27227:27017

  ## Shards 03
  shard03-x:
    image: mongo
    container_name: shard-03-receipt-node-x
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27228:27017
    links:
      - shard03-a
      - shard03-b
  shard03-a:
    image: mongo
    container_name: shard-03-receipt-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27229:27017
  shard03-b:
    image: mongo
    container_name: shard-03-receipt-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03-receipt
    volumes:
      - ./scripts:/scripts
    ports:
      - 27230:27017

  